STOP_WORDS = {
    "the", "a", "an", "is", "it", "in", "to", "and", "of", "for", "on",
    "with", "that", "this", "but", "not", "are", "was", "has", "have",
    "had", "be", "been", "will", "can", "do", "does", "did", "i", "my",
    "me", "we", "our", "you", "your", "they", "them", "their", "he",
    "she", "his", "her", "its", "so", "if", "or", "as", "at", "by",
    "from", "up", "out", "no", "all", "just", "about", "very", "too",
    "also", "than", "then", "when", "what", "which", "who", "how",
    "would", "could", "should", "there", "here", "more", "some", "any",
    "other", "only", "even", "after", "before", "because", "while",
    "where", "why", "each", "every", "both", "few", "most", "own",
    "same", "such", "into", "over", "through", "between", "during",
    "get", "got", "like", "one", "two", "much", "many", "make",
    "made", "well", "back", "still", "way", "use", "used", "app",
    "non", "che", "di", "il", "la", "le", "lo", "un", "una", "per",
    "con", "del", "della", "delle", "dei", "degli", "nel", "nella",
    "nelle", "nei", "negli", "sul", "sulla", "sulle", "sui", "sugli",
    "al", "alla", "alle", "ai", "agli", "da", "come", "sono", "si",
    "mi", "ci", "vi", "ti", "se", "ma", "ed", "ha", "ho", "più",
    "anche", "solo", "essere", "stato", "stata", "molto", "tutto",
    "questa", "questo", "questi", "queste", "poi", "già", "dopo",
    "prima", "sempre", "mai", "ogni", "altro", "altra", "altri",
    "altre", "suo", "sua", "suoi", "sue", "mio", "mia", "miei",
    "mie", "tuo", "tua", "tuoi", "tue", "loro", "nostro", "nostra",
    "vostro", "vostra", "fatto", "fare", "può", "però", "cosa",
    "dove", "quando", "perché", "tra", "fra", "ancora", "così",
    "bene", "male", "ora", "qui", "proprio", "senza", "cui",
    "oppure", "fino", "verso", "sopra", "sotto", "fuori", "dentro",
    "parte", "volta", "anno", "anni", "giorno", "giorni",
}

POSITIVE_WORDS = {
    "great", "excellent", "amazing", "love", "best", "perfect", "awesome",
    "fantastic", "good", "wonderful", "helpful", "easy", "beautiful",
    "recommend", "useful", "nice", "brilliant", "superb", "outstanding",
    "intuitive", "smooth", "fast", "reliable", "convenient", "favorite",
    "enjoy", "happy", "pleased", "satisfied", "impressive", "simple",
    "clean", "elegant", "powerful", "efficient", "quick", "stable",
    "ottimo", "ottima", "eccellente", "fantastico", "fantastica",
    "perfetto", "perfetta", "bellissimo", "bellissima", "stupendo",
    "stupenda", "comodo", "comoda", "utile", "facile", "veloce",
    "affidabile", "consiglio", "consigliato", "pratico", "pratica",
    "funziona", "funzionale", "intuitivo", "intuitiva", "soddisfatto",
    "soddisfatta", "contento", "contenta", "bravi", "bravo", "brava",
    "migliore", "semplice", "efficiente", "stabile", "meraviglioso",
    "meravigliosa", "adoro", "eccezionale", "splendido", "splendida",
}

NEGATIVE_WORDS = {
    "bad", "terrible", "horrible", "worst", "hate", "awful", "poor",
    "useless", "broken", "slow", "crash", "bug", "error", "annoying",
    "frustrating", "disappointing", "waste", "ugly", "complicated",
    "confusing", "unreliable", "expensive", "laggy", "glitch",
    "freeze", "stuck", "problem", "issue", "fail", "failed", "spam",
    "scam", "sucks", "unusable", "nightmare", "ridiculous", "lacking",
    "pessimo", "pessima", "terribile", "orribile", "brutto", "brutta",
    "lento", "lenta", "inutile", "rotto", "rotta", "crash",
    "errore", "fastidioso", "fastidiosa", "frustrante", "deludente",
    "complicato", "complicata", "confuso", "confusa", "costoso",
    "costosa", "problema", "problemi", "difetto", "difetti",
    "blocca", "bloccato", "bloccata", "peggiore", "schifo",
    "vergogna", "vergognoso", "vergognosa", "incapaci",
    "malfunzionamento", "disastro", "disastroso", "disastrosa",
}

NON_APP_CATEGORIES = {
    "pricing": {
        "price", "pricing", "cost", "expensive", "cheap", "fee", "fees",
        "subscription", "subscriptions", "subscribe", "payment", "pay",
        "charge", "charged", "charges", "billing", "bill", "bills",
        "refund", "refunds", "money", "euro", "euros", "dollar", "dollars",
        "purchase", "purchases", "bought", "buy", "buying", "afford",
        "overpriced", "overcharge", "premium", "trial", "free", "freemium",
        "in-app", "iap", "microtransaction", "microtransactions",
        "prezzo", "prezzi", "costo", "costi", "costoso", "costosa",
        "abbonamento", "abbonamenti", "abbonare", "pagamento", "pagamenti",
        "pagare", "addebito", "addebitato", "addebitati", "addebiti",
        "rimborso", "rimborsi", "soldi", "spesa", "spese", "gratis",
        "gratuito", "gratuita", "acquisto", "acquisti", "comprare",
        "canone", "tariffe", "tariffa", "commissione", "commissioni",
    },
    "support": {
        "support", "customer service", "helpdesk", "help desk", "ticket",
        "tickets", "agent", "agents", "operator", "operators", "call center",
        "callcenter", "hotline", "representative", "representatives",
        "response time", "waiting", "waited", "wait", "hold", "queue",
        "unresponsive", "rude", "unhelpful", "ignored", "assistenza",
        "operatore", "operatori", "servizio clienti", "centralino",
        "risposta", "attesa", "aspettare", "aspettato", "ignorato",
        "ignorata", "maleducato", "maleducata", "chiamata", "chiamate",
        "contattare", "contatto", "reclamo", "reclami", "segnalazione",
    },
    "policy": {
        "policy", "policies", "terms", "conditions", "agreement",
        "regulation", "regulations", "compliance", "legal", "contract",
        "contracts", "clause", "clauses", "privacy", "gdpr", "data protection",
        "unfair", "deceptive", "misleading", "scam", "fraud", "fraudulent",
        "politica", "politiche", "condizioni", "contratto", "contratti",
        "clausola", "clausole", "regolamento", "normativa", "normative",
        "inganno", "ingannevole", "truffa", "truffatori", "frode",
        "scorretto", "scorrettezza", "illecito", "trasparenza",
    },
    "external": {
        "branch", "branches", "office", "offices", "location", "locations",
        "employee", "employees", "staff", "personnel", "manager", "managers",
        "atm", "atms", "cashier", "teller", "counter", "physical",
        "in person", "in-person", "visit", "visited", "filiale", "filiali",
        "sede", "sedi", "ufficio", "uffici", "sportello", "sportelli",
        "dipendente", "dipendenti", "personale", "direttore", "direttori",
        "bancomat", "cassa", "cassiere", "consulente", "consulenti",
        "promotore", "promotori", "promotrice", "appuntamento",
    },
}

APP_RELATED_KEYWORDS = {
    "app", "application", "update", "updates", "updated", "version",
    "install", "installed", "download", "downloaded", "interface", "ui",
    "ux", "design", "screen", "screens", "button", "buttons", "menu",
    "navigation", "navigate", "loading", "load", "loads", "login",
    "log in", "logout", "sign in", "signin", "signup", "sign up",
    "crash", "crashes", "crashed", "crashing", "bug", "bugs", "buggy",
    "glitch", "glitches", "freeze", "freezes", "frozen", "slow",
    "fast", "speed", "performance", "lag", "laggy", "responsive",
    "notification", "notifications", "push", "alert", "alerts",
    "feature", "features", "function", "functions", "functionality",
    "fingerprint", "face id", "faceid", "biometric", "touch id",
    "widget", "widgets", "dark mode", "layout", "tab", "tabs",
    "scroll", "scrolling", "swipe", "tap", "click", "search",
    "filter", "sort", "display", "displaying", "shows", "showing",
    "applicazione", "aggiornamento", "aggiornamenti", "aggiornata",
    "versione", "installare", "installata", "scaricare", "scaricata",
    "interfaccia", "schermata", "schermate", "pulsante", "pulsanti",
    "navigazione", "caricamento", "accesso", "accedere", "registrazione",
    "blocca", "bloccata", "bloccato", "errore", "errori",
    "lento", "lenta", "veloce", "prestazioni", "notifica", "notifiche",
    "funzione", "funzioni", "funzionalità", "impronta", "riconoscimento",
}

CATEGORY_LABELS = {
    "pricing": "Pricing & Billing",
    "support": "Customer Support",
    "policy": "Policy & Terms",
    "external": "Branches & Staff",
}
